version: "3"
services:
  client:
    image: aservera/cncgit:latest
    container_name: cncgit
    command: bin/bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "831:830"
    networks:
      - test
    volumes:
      - ./shared:/shared

networks:
  test:
    driver: bridge
